## Shopping Análises

In [11]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("shopping_trends.csv")

df

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Cash,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,Cash,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,PayPal,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Credit Card,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,PayPal,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Bank Transfer,Store Pickup,No,No,33,Venmo,Quarterly

In [4]:
df = df.drop(columns="Customer ID")

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       3900 non-null   int64
 1   Gender                    3900 non-null   object
 2   Item Purchased            3900 non-null   object
 3   Category                  3900 non-null   object
 4   Purchase Amount (USD)     3900 non-null   int64
 5   Location                  3900 non-null   object
 6   Size                      3900 non-null   object
 7   Color                     3900 non-null   object
 8   Season                    3900 non-null   object
 9   Review Rating             3900 non-null   float64
 10  Subscription Status       3900 non-null   object
 11  Payment Method            3900 non-null   object
 12  Shipping Type             3900 non-null   object
 13  Discount Applied          3900 non-null   object
 14  Promo Code Used           3900 non-null   object
 15  Previous Purchases        3900 non-null   int64
 16  Preferred Payment Method  3900 non-null   object
 17  Frequency of Purchases    3900 non-null   object
dtypes: float64(1), int64(3), object(14)
memory usage: 548.6+ KB

In [13]:
valores = df['Age'].unique()
np.sort(valores)

array([18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70])

In [16]:
bins = [18, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 150]
labels = ['18-25', '25-30', '30-35', '35-40', '40-45', '45-50', '50-55', '55-60', '60-65', '65-70', '70+']

df['faixas'] = pd.cut(df['Age'], bins=bins, labels=labels)

In [18]:
contagem = df['faixas'].value_counts()
print(contagem)

faixas
18-25    502
55-60    382
45-50    382
25-30    378
50-55    371
60-65    368
40-45    368
30-35    364
35-40    361
65-70    355
70+        0
Name: count, dtype: int64

In [20]:
contagem_percentual = round(df['faixas'].value_counts(normalize=True) * 100, 2)
print(contagem_percentual)

faixas
18-25    13.10
55-60     9.97
45-50     9.97
25-30     9.87
50-55     9.68
60-65     9.61
40-45     9.61
30-35     9.50
35-40     9.42
65-70     9.27
70+       0.00
Name: proportion, dtype: float64